---
- name: Drop OPSS schema (13.4 and below)
  shell: >
    {{ oracle_home }}/sysman/admin/emdrep/bin/SecurityRepManager
    -action dropRepository
    -connectString "{{ repo_conn_str }}"
    -dbUser sys -dbPassword "{{ sys_password }}"
    -component opss
    -schemaPrefix SYSMAN122130
    -schemaPassword "{{ sysman_password }}"
  register: drop_result
  become_user: oracle

- name: Validate OPSS schema drop
  fail:
    msg: "Failed to drop OPSS schema"
  when: "'completed successfully' not in drop_result.stdout"

- name: Create OPSS schema
  shell: >
    {{ oracle_home }}/sysman/admin/emdrep/bin/SecurityRepManager
    -action createRepository
    -connectString "{{ repo_conn_str }}"
    -dbUser sys -dbPassword "{{ sys_password }}"
    -component opss
    -schemaPrefix SYSMAN122130
    -schemaPassword "{{ sysman_password }}"
  register: create_result
  become_user: oracle

- name: Validate OPSS schema creation
  fail:
    msg: "Failed to create OPSS schema"
  when: "'completed successfully' not in create_result.stdout"
