---
- name: Secure EMKey after clone
  become: yes
  become_user: "{{ source.os_user }}"
  environment:
    ORACLE_HOME: "{{ source.oms_home }}"
  shell: >
    echo "{{ source.sysman_password }}"
    | {{ source.oms_home }}/bin/emctl config emkey -remove_from_repos
  args:
    executable: /bin/bash
  no_log: true
  register: secure_emkey_result
  changed_when: "'completed' in secure_emkey_result.stdout.lower()"
  failed_when: secure_emkey_result.rc != 0

- name: "Provide output for em copy"
  debug:
    msg:
      - "EMKey copy stdout: {{ secure_emkey_result.stdout }}"
      - "EMKey copy stderr: {{ secure_emkey_result.stderr }}"
      - "Return code: {{ secure_emkey_result.rc }}"
  when: secure_emkey_result is defined
