---
- name: Perform Silent OMS clone
  become: yes
  become_user: "{{ target.os_user }}"
  ansible.builtin.shell: |
      {{ target.oms_home }}/bin/omsca new -nostart \
      -EM_DOMAIN_NAME {{ target.em_domain_name }} \
      -NM_USER nodemanager \
      -NM_PWD {{ target.node_manager_password }} \
      -AS_USERNAME weblogic \
      -AS_PASSWORD {{ target.as_user_password }} \
      -MS_HTTPS_PORT {{ target.msport }} \
      -REP_CONN_STR '{{ target.repo_conn_str }}' \
      -AS_HOST {{ target.oms_host_name }} \
      -AS_HTTPS_PORT {{ target.admin_server_https_port }} \
      -CONFIG_HOME {{ target.oms_config_files_path }} \
      -EM_INSTANCE_HOST {{ target.oms_host_name }} \
      -EM_UPLOAD_PORT {{ target.upload_http_port }} \
      -EM_UPLOAD_HTTPS_PORT {{ target.upload_https_port }} \
      -REP_PWD {{ target.sysman_password }} \
      -REG_PWD {{ target.agent_reg_password }} \
      -reuseOpssStore
  args:
    chdir: "{{ target.oms_home }}/bin"
    executable: /bin/bash
  register: clone_oms_result
  changed_when: clone_oms_result.rc == 0
  failed_when: clone_oms_result.rc != 0

- name: Display OMS clone output
  ansible.builtin.debug:
    msg:
      - "Stdout: {{ clone_oms_result.stdout | trim }}"
      - "Stderr: {{ clone_oms_result.stderr | trim }}"
      - "Return code: {{ clone_oms_result.rc }}"
