---
# Name: OEM Clone Automation
# Created by: Arun Yadav
# Playbook to clone OEM from one server to another

- name: Perform OMS Clone Prereqs on Target
  hosts: "{{ target_server }}"
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: Install Required Packages on Target OEM server
      import_role:
        name: install_req_packages

    - name: Install Agent on Target OEM server
      import_role:
        name: install_agent

    - name: Paste OMS binary from Source to Target OEM server
      import_role:
        name: paste_binary
      run_once: true

- name: Final OMS clone and setup on Target OEM server
  hosts: "{{ target_server }}"
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: Clone OMS software
      import_role:
        name: clone_oms

    - name: Configure OEM plugins
      import_role:
        name: configure_plugin

    - name: Start OMS service
      import_role:
        name: start_oms

    - name: Post-configuration checks
      import_role:
        name: post_config

- name: Finally secure the EMKey on Source
  hosts: "{{ source_server }}"
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: Secure EM Key
      import_role:
        name: secure_em_key
