---
# Name: OEM Clone Automation
# Created by: Arun Yadav
# Playbook to clone OEM from one server to another

- name: Run prereq on Source OEM server
  hosts: "{{ source_server }}"
  become: true
  become_user: "{{ source.os_user }}"
  vars_files:
    - vars/main.yml
  tasks:
    - name: Check prerequisite
      import_role:
        name: check_prereq
      run_once: true

    - name: Copy EMKey to repository
      import_role:
        name: copy_emkey
      run_once: true

    - name: Prepare OMS binaries on Source
      import_role:
        name: prepare_binaries

    - name: Prepare agent software
      import_role:
        name: prepare_agent_software
