---
# Name: OEM Clone Automation
# Created by: Arun Yadav
# Playbook to clone OEM from one server to another

- name: Run prereq on Source OEM server
  hosts: "{{ source_server }}"
  become: true
  become_user: "{{ source.os_user }}"
  vars_files:
    - vars/main.yml
  tasks:
    - name: check_prereq role
      import_role:
        name: check_prereq
      run_once: true

- name: Copy EMKey to repository
  hosts: "{{ source_server }}"
  become: true
  become_user: "{{ source.os_user }}"
  vars_files:
    - vars/main.yml
  tasks:
    - name: copy_emkey role
      import_role:
        name: copy_emkey
      run_once: true

# - name: Validate OEM repository DB on Target OEM server
#   hosts: "{{ target_server }}"
#   become: true
#   tasks:
#     - name: clone_repo_db role
#       import_role:
#         name: clone_repo_db

- name: Prepare OMS binaries on Source OEM server
  hosts: "{{ source_server }}"
  become: true
  vars_files:
    - vars/main.yml
  become_user: "{{ source.os_user }}"
  tasks:
    - name: Prepare binaries
      import_role:
        name: prepare_binaries
## Testing completed successfully until here...
