---
- name: Recreate OMS_HOME on TARGET OMS using pasteBinary.sh
  become: yes
  become_user: "{{ target.os_user }}"
  ansible.builtin.shell: |
    "{{ target.agent_base }}/agent_{{target.oem_version}}.0.0.0/oracle_common/bin/pasteBinary.sh" \
    -javaHome "{{ target.agent_base }}/agent_{{target.oem_version}}.0.0.0/oracle_common/jdk/" \
    -archiveLoc "{{ oms_clone_dir }}/oms_clone.jar" \
    -targetOracleHomeLoc "{{ target.oms_home }}" \
    -executeSysPrereqs false \
    -silent true
  args:
    executable: /bin/bash
  register: paste_binary_result
  changed_when: paste_binary_result.rc == 0
  failed_when: paste_binary_result.rc != 0

- name: Display TARGET OMS_HOME install results
  ansible.builtin.debug:
    msg:
      - "Stdout: {{ paste_binary_result.stdout | trim }}"
      - "Stderr: {{ paste_binary_result.stderr | trim }}"
      - "Return code: {{ paste_binary_result.rc }}"
  when: paste_binary_result is defined

- name: Rename emInstanceMapping.properties for backup
  become: true
  become_user: "{{ target.os_user }}"
  ansible.builtin.command:
    cmd:
      - mv
      - "{{ target.oms_home }}/sysman/config/emInstanceMapping.properties"
      - "{{ target.oms_home }}/sysman/config/emInstanceMapping.properties.bak"
    creates: "{{ target.oms_home }}/sysman/config/emInstanceMapping.properties.bak"
    removes: "{{ target.oms_home }}/sysman/config/emInstanceMapping.properties"
  register: rename_em_mapping
  changed_when: rename_em_mapping.rc == 0
  failed_when: rename_em_mapping.rc != 0
