---
- name: Clone repository DB using RMAN
  debug:
    msg: 
    - "Manual Clone - Using RMAN to Safely Clone a Database onto the Same Storage as the Source Database (Doc ID 2289796.1)"
    - "Duplicate Oracle 19c Database- https://docs.oracle.com/en/database/oracle/oracle-database/19/bradv/rman-duplicating-databases.html#GUID-F31F9FCE-B610-49EB-B9DB-44B9AA4E838F"

- name: Validate cloned DB status
  shell: |
    sqlplus / as sysdba <<EOF
    SELECT username, account_status FROM dba_users
    WHERE username IN ('SYSMAN', 'MGMT_VIEW');
    EOF
  register: db_status
  become_user: oracle
